export const SET_REGIONS = 'SET_REGIONS';
export const SET_CITIES = 'SET_CITIES';
export const SET_SUBURBS = 'SET_SUBURBS';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const SEARCH_PROPERTIES = 'SEARCH_PROPERTIES';
export const SET_PROPERTIES = 'SET_PROPERTIES';
export const SET_PROPERTY_DETAILS = 'SET_PROPERTY_DETAILS';
export const ADD_PROPERTY = 'ADD_PROPERTY';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';

export const MANAGE_SET_PROPERTY = 'MANAGE_SET_PROPERTY';
export const MANAGE_CLEAR_PROPERTY = 'MANAGE_CLEAR_PROPERTY';
export const MANAGE_SET_PROPERTIES = 'MANAGE_SET_PROPERTIES';
export const MANAGE_DELETE_PROPERTY = 'MANAGE_DELETE_PROPERTY';

export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
